# SPDX-License-Identifier: Apache-2.0
load("@rules_nvc//build/nvc:rules.bzl", "wave_view")
load(
    "@rules_vivado//build/vivado:rules.bzl",
    "vivado_generics",
    "vivado_library",
    "vivado_place_and_route",
    "vivado_program_device",
    "vivado_project",
    "vivado_simulation",
    "vivado_synthesis",
)

package(default_visibility = ["//visibility:public"])

vivado_library(
    name = "testing",
    standard = "2008",
    srcs = [
        "//testing:srcs_no_vunit",
    ],
    deps = [
        "//ip/tl/tool.vivado:tl",
        "//ip/wb/tool.vivado:wb",
        "//third_party/xilinx:unisim",
    ],
)
