# SPDX-License-Identifier: Apache-2.0
# See LICENSE file.
load(
    "@rules_vivado//build/vivado:rules.bzl",
    "vivado_library",
)

package(default_visibility = ["//visibility:public"])

vivado_library(
    name = "wb_uart",
    standard = "2008",
    srcs = ["//ip/wb_uart"],
    deps = [
        "//ip/wb/tool.vivado:wb",
        "//third_party/uart:third_party_uart",
    ],
)
